const DEFAULT_DOMAINS=[{name:"Athletic Mastery",description:"Body, speed, coordination, recovery, nutrition, and sport-specific excellence.",skills:["Train deliberately","Review performance film","Track recovery","Build mobility","Log nutrition"]},{name:"Logic & Mathematics",description:"Reasoning, proofs, statistics, finance math, systems thinking, and decision analysis.",skills:["Solve hard problems","Write explanations","Learn statistics","Practice mental math","Analyze decisions"]},{name:"Science & Engineering",description:"Physics, chemistry, biology, technology, experimentation, and building useful things.",skills:["Run experiments","Build prototypes","Study mechanisms","Document results","Explain like a teacher"]},{name:"History & Civilization",description:"Power, institutions, war, diplomacy, economics, culture, and human pattern recognition.",skills:["Read primary sources","Make timelines","Compare civilizations","Write briefs","Study strategy"]},{name:"Business & Wealth",description:"Entrepreneurship, investing, sales, negotiation, accounting, and market understanding.",skills:["Analyze companies","Build offers","Practice sales","Track money","Study incentives"]},{name:"Communication & Leadership",description:"Writing, speaking, rhetoric, social intelligence, charisma, and command presence.",skills:["Speak daily","Write clearly","Practice scenarios","Ask better questions","Lead small actions"]},{name:"Philosophy & Theology",description:"Wisdom, ethics, spiritual formation, worldview, meaning, and moral discipline.",skills:["Read scripture","Journal correction","Study philosophy","Clarify values","Act with integrity"]},{name:"Arts & Culture",description:"Drawing, design, music, literature, photography, taste, beauty, and creative output.",skills:["Sketch","Shoot photos","Study masterpieces","Create weekly","Critique your work"]}];
const DEFAULT_MISSIONS=[{title:"Read 20 pages from a serious book and write 5 bullet takeaways.",domain:"History & Civilization",xp:30,completed:false},{title:"Solve one hard math, logic, or coding problem without quitting early.",domain:"Logic & Mathematics",xp:35,completed:false},{title:"Train one physical quality with deliberate intent, then log the result.",domain:"Athletic Mastery",xp:35,completed:false},{title:"Write one clear paragraph explaining a complex idea simply.",domain:"Communication & Leadership",xp:25,completed:false},{title:"Study one business, market, or money concept and identify how it creates value.",domain:"Business & Wealth",xp:25,completed:false},{title:"Do one act that strengthens discipline, honesty, faith, or moral courage.",domain:"Philosophy & Theology",xp:30,completed:false},{title:"Create something visual: sketch, photo, layout, diagram, or design study.",domain:"Arts & Culture",xp:25,completed:false},{title:"Learn one scientific mechanism and explain the cause-and-effect chain.",domain:"Science & Engineering",xp:30,completed:false}];
const RANKS=[{xp:0,title:"Initiate"},{xp:250,title:"Apprentice Generalist"},{xp:750,title:"Disciplined Scholar"},{xp:1500,title:"Operator-Thinker"},{xp:3000,title:"Renaissance Builder"},{xp:5000,title:"Polymath Candidate"},{xp:8000,title:"Strategic Polymath"},{xp:12000,title:"Master Integrator"}];
const saved=localStorage.getItem("polymathPathState");const state=saved?JSON.parse(saved):{operationTitle:"Project Polymath",domains:DEFAULT_DOMAINS,missions:DEFAULT_MISSIONS,projects:[],outputs:[],reviews:[],archive:[],xp:0,streak:0,lastActiveDate:null,todayMissionIds:[]};let activeMissionIndex=null;
const $=id=>document.getElementById(id);const save=()=>localStorage.setItem("polymathPathState",JSON.stringify(state));const date=()=>new Date().toISOString().slice(0,10);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function ensureDaily(){const t=date();if(state.lastActiveDate!==t){state.missions.forEach(m=>m.completed=false);state.todayMissionIds=[];if(state.lastActiveDate){const diff=Math.round((new Date(t)-new Date(state.lastActiveDate))/86400000);state.streak=diff===1?state.streak+1:1}else state.streak=1;state.lastActiveDate=t;save()}}
function rankFor(xp){let r=RANKS[0];for(const x of RANKS)if(xp>=x.xp)r=x;return r}function nextRank(xp){return RANKS.find(r=>r.xp>xp)||RANKS[RANKS.length-1]}function domainXp(d){return state.outputs.filter(o=>o.domain===d).reduce((s,o)=>s+Number(o.xp||0),0)}
function populateSelects(){["missionDomain","projectDomain"].forEach(id=>{const sel=$(id),v=sel.value;sel.innerHTML=state.domains.map(d=>`<option>${esc(d.name)}</option>`).join("");if(v)sel.value=v})}
function render(){ensureDaily();$("operationTitle").textContent=state.operationTitle;const done=state.missions.filter(m=>m.completed),score=done.reduce((s,m)=>s+Number(m.xp||0),0);$("dailyScore").textContent=score;$("streak").textContent=state.streak;$("completedCount").textContent=done.length;$("outputCount").textContent=state.outputs.length;const r=rankFor(state.xp),n=nextRank(state.xp);$("rankTitle").textContent=r.title;$("xpValue").textContent=state.xp;$("xpFill").style.width=`${n.xp===r.xp?100:Math.min(100,((state.xp-r.xp)/Math.max(1,n.xp-r.xp))*100)}%`;populateSelects();renderMissions();renderDomains();renderProjects();renderReviews();renderArchive();renderCompass()}
function missionCard(m,i,del=false){return `<div class="mission"><div><h4>${m.completed?"✓ ":""}${esc(m.title)}</h4><p>${esc(m.domain)} · ${m.xp} XP</p><span class="badge">${m.completed?"Completed":"Requires proof"}</span></div><div><button data-complete="${i}" ${m.completed?"disabled":""}>Log</button>${del?` <button class="danger" data-delete-mission="${i}">Delete</button>`:""}</div></div>`}
function renderMissions(){const t=$("todayMissions"),a=$("allMissions");t.innerHTML=state.todayMissionIds.length?state.todayMissionIds.map(i=>missionCard(state.missions[i],i)).join(""):`<p class="muted">No daily set generated yet. Generate today’s missions to start execution.</p>`;a.innerHTML=state.missions.map((m,i)=>missionCard(m,i,true)).join("");document.querySelectorAll("[data-complete]").forEach(b=>b.onclick=()=>openOutput(Number(b.dataset.complete)));document.querySelectorAll("[data-delete-mission]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.deleteMission);state.missions.splice(i,1);state.todayMissionIds=state.todayMissionIds.filter(id=>id!==i).map(id=>id>i?id-1:id);save();render()})}
function renderDomains(){$("domainGrid").innerHTML=state.domains.map((d,i)=>`<div class="domain-card"><h4>${esc(d.name)}</h4><p>${esc(d.description)}</p><span class="badge">${domainXp(d.name)} XP earned</span><ul>${d.skills.map(s=>`<li>${esc(s)}</li>`).join("")}</ul><button class="danger" data-delete-domain="${i}">Delete</button></div>`).join("");document.querySelectorAll("[data-delete-domain]").forEach(b=>b.onclick=()=>{if(state.domains.length<=1)return;state.domains.splice(Number(b.dataset.deleteDomain),1);save();render()})}
function renderCompass(){$("compass").innerHTML=state.domains.map(d=>{const xp=domainXp(d.name),pct=Math.min(100,xp/5);return `<div class="compass-row"><div class="compass-top"><span>${esc(d.name)}</span><span>${xp} XP</span></div><div class="compass-bar"><span style="width:${pct}%"></span></div></div>`}).join("")}
function renderProjects(){const list=$("projectList");list.innerHTML=state.projects.length?state.projects.map((p,i)=>`<div class="project"><h4>${esc(p.title)}</h4><p>${esc(p.domain)}</p><p>${esc(p.definition)}</p><span class="badge">${p.status}</span><br><button data-toggle-project="${i}">${p.status==="Active"?"Mark Complete":"Reopen"}</button> <button class="danger" data-delete-project="${i}">Delete</button></div>`).join(""):`<p class="muted">No projects yet. Add a capstone that produces evidence.</p>`;document.querySelectorAll("[data-toggle-project]").forEach(b=>b.onclick=()=>{const p=state.projects[Number(b.dataset.toggleProject)];p.status=p.status==="Active"?"Complete":"Active";if(p.status==="Complete")state.xp+=100;save();render()});document.querySelectorAll("[data-delete-project]").forEach(b=>b.onclick=()=>{state.projects.splice(Number(b.dataset.deleteProject),1);save();render()})}
function renderReviews(){$("reviewHistory").innerHTML=state.reviews.slice().reverse().map(r=>`<div class="review-item"><p class="eyebrow">${esc(r.date)}</p><p><strong>Learned:</strong> ${esc(r.learned)}</p><p><strong>Fake progress:</strong> ${esc(r.fake)}</p><p><strong>Proof:</strong> ${esc(r.proof)}</p><p><strong>Priority:</strong> ${esc(r.priority)}</p></div>`).join("")}
function renderArchive(){$("archiveList").innerHTML=state.archive.length?state.archive.slice().reverse().map(a=>`<div class="archive-item"><p class="eyebrow">${esc(a.date)}</p><h4>${esc(a.title)}</h4><p>${a.xp} XP · ${a.outputs} outputs · ${a.projects} projects</p></div>`).join(""):`<p class="muted">No archived operations yet.</p>`}
function openOutput(i){activeMissionIndex=i;$("dialogMission").textContent=state.missions[i].title;$("outputText").value="";$("outputDialog").showModal()}
function shuffle(arr){for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active-view"));b.classList.add("active");$(b.dataset.view).classList.add("active-view")});
$("generateTodayBtn").onclick=()=>{const ids=[...state.missions.keys()].filter(i=>!state.missions[i].completed);shuffle(ids);state.todayMissionIds=ids.slice(0,Math.min(5,ids.length));save();render()};
$("missionForm").onsubmit=e=>{e.preventDefault();state.missions.push({title:$("missionTitle").value.trim(),domain:$("missionDomain").value,xp:Number($("missionXp").value),completed:false});e.target.reset();save();render()};
$("projectForm").onsubmit=e=>{e.preventDefault();state.projects.push({title:$("projectTitle").value.trim(),domain:$("projectDomain").value,definition:$("projectDefinition").value.trim(),status:"Active"});e.target.reset();save();render()};
$("outputForm").onsubmit=e=>{const m=state.missions[activeMissionIndex];if(!m)return;const text=$("outputText").value.trim();if(!text)return;m.completed=true;state.outputs.push({date:new Date().toISOString(),mission:m.title,domain:m.domain,xp:m.xp,text});state.xp+=Number(m.xp||0);save();setTimeout(render,0)};
$("saveReviewBtn").onclick=()=>{state.reviews.push({date:date(),learned:$("reviewLearned").value.trim(),fake:$("reviewFake").value.trim(),proof:$("reviewProof").value.trim(),priority:$("reviewPriority").value.trim()});["reviewLearned","reviewFake","reviewProof","reviewPriority"].forEach(id=>$(id).value="");state.xp+=75;save();render()};
$("addDomainBtn").onclick=()=>{const name=prompt("Domain name?");if(!name)return;state.domains.push({name,description:prompt("Domain description?")||"Custom domain.",skills:["Define core skills","Create missions","Produce evidence"]});save();render()};
$("newOperationBtn").onclick=()=>{state.archive.push({date:date(),title:state.operationTitle,xp:state.xp,outputs:state.outputs.length,projects:state.projects.length});state.operationTitle=prompt("New operation title?","Project Polymath II")||"Project Polymath II";state.missions.forEach(m=>m.completed=false);state.projects=[];state.outputs=[];state.reviews=[];state.todayMissionIds=[];state.xp=0;save();render()};
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`polymath-path-backup-${date()}.json`;a.click();URL.revokeObjectURL(url)};
$("importInput").onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,imported);save();render()}catch{alert("Invalid backup file.")}};reader.readAsText(file)};
$("resetBtn").onclick=()=>{if(confirm("Reset all current app data? Export first if you care about it.")){localStorage.removeItem("polymathPathState");location.reload()}};
render();
